### PR TITLE
fix: handle not javascript modules

### PR DESCRIPTION
**Pull request by alexander-akait**
BREAKING CHANGE: loader don't generate comment by default

This PR contains a:

- [x] **bugfix**
- [ ] new **feature**
- [ ] **code refactor**
- [x] **test update** 
- [ ] **typo fix**
- [ ] **metadata update**

### Motivation / Use-Case

Don't generate comment by default because it can break not js assets (like css, html and etc). Better avoid any code generation inside loader.

### Breaking Changes

Yes

### Additional Info

No

### CODE REVIEW

**Comment by endiliey** [comment]
Thanks. This PR should close out #21 and #20

**Comment by alexander-akait** [comment]
@endiliey in theory we can add option `data` to allow generate any custom information (like `/* It was removed because it is polyfill */` - using ` { test: path.resolve(__dirname, 'polyfill.js'), loader: 'null-loader', options: { data: '/* It was removed because it is polyfill */'} }`), but i thinks it is no need, anyway if somebody need this - PR welcome.

**Comment by tubalmartin** [comment]
Thank you fore releasing a better yet solution and sorry for not committing the tests in #20 i've been really busy these past days.

**Comment by alexander-akait** [comment]
@tubalmartin don't worry, sometimes i seem a little slow but i have a lot of issues and PRs

**Pull request merged**
